name: Publish Docker releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * */7"

jobs:
  publish-docker-image-latest:
    runs-on: ubuntu-latest
    name: Publish Docker image from master branch

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dangmai/nextcloud-gui
          push: true
          tags: latest
